# Generated by Django 4.0.1 on 2022-02-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_wishes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
